## 服务器端口
#server:
#  port: 8090
##  servlet:
##    context-path: /mydemo
#
## 日志
#logging:
#  level:
#    root: info # root级别
#    com.example.tuimian: warn # package级别
#  file:
#    name: logs/system.log
#
## JPA
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update # Update the schema if necessary.
#    show-sql: true
#  # 数据源
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mydemo?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: yhz1651
#    # Druid数据库连接池配置
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall,slf4j
#      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.jif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      stat-view-servlet:
#        url-pattern: "/druid/*"
##        allow: 127.0.0.1,192.168.31.76
##        deny: 192.168.1.73
#        reset-enable: false
#        login-username: admin
#        login-password: admin123456
#
